//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_cyberneticAvatar : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 Axis2d
        {
            get
            {
                return SteamVR_Actions.cyberneticAvatar_Axis2d;
            }
        }
        
        public virtual SteamVR_Action_Boolean IsPressAxis2d
        {
            get
            {
                return SteamVR_Actions.cyberneticAvatar_IsPressAxis2d;
            }
        }
        
        public virtual SteamVR_Action_Boolean IsLongPressAxis2d
        {
            get
            {
                return SteamVR_Actions.cyberneticAvatar_IsLongPressAxis2d;
            }
        }
        
        public virtual SteamVR_Action_Boolean IsTouchAxis2d
        {
            get
            {
                return SteamVR_Actions.cyberneticAvatar_IsTouchAxis2d;
            }
        }
        
        public virtual SteamVR_Action_Boolean IsPressSelectButton
        {
            get
            {
                return SteamVR_Actions.cyberneticAvatar_IsPressSelectButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean IsLongPressSelectButton
        {
            get
            {
                return SteamVR_Actions.cyberneticAvatar_IsLongPressSelectButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean IsPressCancelButton
        {
            get
            {
                return SteamVR_Actions.cyberneticAvatar_IsPressCancelButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean IsLongPressCancelButton
        {
            get
            {
                return SteamVR_Actions.cyberneticAvatar_IsLongPressCancelButton;
            }
        }
        
        public virtual SteamVR_Action_Single TriggerValue
        {
            get
            {
                return SteamVR_Actions.cyberneticAvatar_TriggerValue;
            }
        }
    }
}
